name: 'Generate Labels'

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  label:
    name: 'Label PR based on title'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}